# For development purpose only
version: "3.7"

services:
  remote-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "11451:11451"

    volumes:
      - ./:/presto-pipeline/