# For development purpose only
version: "3.7"

services:
  remote-1:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"

    volumes:
      - ./:/presto-data/
      - /nfsmemdisk/presto:/presto-contest